services:
#  db:
#    image: postgres:latest
#    restart: always
  nginx:
    image: nginx:latest
    build:
      context: nginx
      dockerfile: Dockerfile

    ports:
      - 1337:80

      # Storage volumes
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web
    restart: "on-failure"


  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: filemanager

    ports:
      - "8000:8000"

    volumes:
#      - .:/app/
      - ./filemanager:/app/filemanager

    restart: always

    env_file:
      - .env

    environment:
      DJANGO_SETTINGS_MODULE: filemanager.settings
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1


#docker compose up --build