services:
#  db:
#    image: postgres:latest
#    restart: always
#  nginx:
#    image: nginx
#    build:
#      context: nginx
#      dockerfile: Dockerfile
#    ports:
#      - 8000:80
#
#      # Storage volumes
#    volumes:
#      - static_volume:/home/app/filemanager/templates/statics
##      - media_volume:/home/app/web/mediafiles
#    depends_on:
#      - app
#    restart: "on-failure"

  app:
    build:
      context: filemanager_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: always
    container_name: app
    env_file:
      - .env

#docker compose up --build