events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;

    upstream django {
        server app:8000;
    }

    server {
        listen 80;
        server_name _;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location /static/ {
            alias /static/;
            autoindex off;
            expires 30d;
        }

        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

